# 061 : Sets 2

my_set = {1, 2, 3, 4, 5}  # set of integers
your_set = {4, 5, 6, 7, 8, 9, 10}  # set of integers

# difference is a method that returns the difference between two sets
print(my_set.difference(your_set))  # {1, 2, 3}

# discard is a method that removes an element from a set if it is a member
my_set.discard(5)  # remove 5 from set
print(my_set)  # {1, 2, 3, 4}

# difference_update is a method that removes all elements of another set from this set
my_set.difference_update(your_set)  # remove all elements of your_set from my_set
print(my_set)  # {1, 2, 3}

# intersection is a method that returns the intersection of two sets as a new set
print(my_set.intersection(your_set))  # set()
print(my_set & your_set)  # set() # TODO: shorthand for intersection

# isdisjoint is a method that returns True if two sets have a null intersection
print(my_set.isdisjoint(your_set))  # True

# issubset is a method that returns True if another set contains this set
print(my_set.issubset(your_set))  # False

# issuperset is a method that returns True if this set contains another set
print(my_set.issuperset(your_set))  # False

# union is a method that returns the union of two sets as a new set
print(my_set.union(your_set))  # {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
print(my_set | your_set)  # {1, 2, 3, 4, 5, 6, 7, 8, 9, 10} # TODO: shorthand for union

# Scroll to bottom to see solution
# You are working for the school Principal. We have a database of school students:
school = {"Bobby", "Tammy", "Jammy", "Sally", "Danny"}
# during class, the teachers take attendance and compile it into a list.
attendance_list = ["Jammy", "Bobby", "Danny", "Sally"]
# using what you learned about sets, create a piece of code that the school principal can use to
# immediately find out who missed class so they can call the parents.
# (Imagine if the list had 1000s of students. The principal can use the lists generated by the teachers
#  + the school database to use python and make his/her job easier):
#  Find the students that miss class!

# Solution: Notice how we don't have to convert the attendance_list to a set...it does it for you.
print(school.difference(attendance_list))  # {'Tammy'}
